services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: polaris_backend:latest
    restart: always
    container_name: polaris_backend
    volumes:
      - .:/app
      - ./volumes/static:/static/
    env_file:
      - .env
    entrypoint: python3 manage.py
    command: runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    container_name: polaris_db
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: