# Generated by Django 5.1.2 on 2025-08-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('technology', models.CharField(max_length=10)),
                ('plmn_id', models.CharField(blank=True, max_length=10, null=True)),
                ('lac', models.IntegerField(blank=True, null=True)),
                ('rac', models.IntegerField(blank=True, null=True)),
                ('tac', models.IntegerField(blank=True, null=True)),
                ('cell_id', models.IntegerField(blank=True, null=True)),
                ('frequency_band', models.CharField(blank=True, max_length=20, null=True)),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('rsrp', models.FloatField(blank=True, null=True)),
                ('rsrq', models.FloatField(blank=True, null=True)),
                ('rscp', models.FloatField(blank=True, null=True)),
                ('ec_no', models.FloatField(blank=True, null=True)),
                ('rxlev', models.FloatField(blank=True, null=True)),
                ('download_rate', models.FloatField(blank=True, null=True)),
                ('upload_rate', models.FloatField(blank=True, null=True)),
                ('ping_response_time', models.FloatField(blank=True, null=True)),
                ('dns_response_time', models.FloatField(blank=True, null=True)),
                ('web_response_time', models.FloatField(blank=True, null=True)),
                ('sms_delivery_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'measurements',
                'ordering': ['-timestamp'],
            },
        ),
    ]
