# Generated by Django 5.1.2 on 2025-08-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='technology',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
